name: Fetch Snow Depth Data and Upload to MapTiler

on:
  schedule:
    - cron: "0 7 * * *" # Every day at 07:00 UTC
  workflow_dispatch:

jobs:
  fetch-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Fetch snow depth data and generate GeoJSON
        run: |
          python -m snow_sensors.cli --output snow_depth_data.geojson --format geojson

      - name: Upload GeoJSON to MapTiler
        env:
          MAPTILER_TOKEN: ${{ secrets.MAPTILER_API_KEY }}
          MAPTILER_TILESET_ID: ${{ secrets.MAPTILER_TILESET_ID }}
        run: |
          if [ -n "$MAPTILER_TILESET_ID" ]; then
            echo "Updating existing tileset: $MAPTILER_TILESET_ID"
            maptiler-cloud tiles ingest --document-id=$MAPTILER_TILESET_ID snow_depth_data.geojson
          else
            echo "Creating new tileset"
            maptiler-cloud tiles ingest snow_depth_data.geojson
          fi

      - name: Upload GeoJSON artifact
        uses: actions/upload-artifact@v4
        with:
          name: snow_depth_geojson
          path: snow_depth_data.geojson
